Check that pytest workflow completed succesfully

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,6 +11,14 @@ jobs:
     name: Push Docker image to Docker Hub
     runs-on: ubuntu-latest
     steps:
+      - name: Check Workflow Pytest & flake8 status
+        run: |
+          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
+            echo "Workflow A was successful"
+          else
+            echo "Workflow A failed"
+            exit 1
+          fi
       - name: Check out the repo
         uses: actions/checkout@v3
       
