Build and push to ECR

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -1,38 +1,45 @@
-name: Build and Push Docker image to Docker Hub
+name: Build and Push Docker Image to AWS ECR
 
 on:
-  workflow_run:
-    workflows:
-      - Python
-    types:
-      - completed
-
+  - push
+  # workflow_run:
+  #   workflows:
+  #     - Python
+  #   types:
+  #     - completed
 jobs:
-  push_to_registry:
-    name: Push Docker image to Docker Hub
+  build-and-push:
+    name: Build and Push to ECR
     runs-on: ubuntu-latest
     steps:
-      - name: Check Workflow Python status
-        run: |
-          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
-            echo "Workflow Python was successful."
-          else
-            echo "Workflow Python failed."
-            exit 1
-          fi
-      - name: Check out the repo
+      # - name: Check Workflow Python status
+      #   run: |
+      #     if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
+      #       echo "Workflow Python was successful."
+      #     else
+      #       echo "Workflow Python failed."
+      #       exit 1
+      #     fi
+      - name: Checkout repo
         uses: actions/checkout@v3
-      
-      - name: Login to Docker Hub
-        uses: docker/login-action@v2
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
         with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-    
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v4
-        with:
-          context: ./
-          file: ./Dockerfile
-          push: true
-          tags: bullfinch38/fastandtraefik-fastapi:latest
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: us-east-1
+
+      - name: Login to ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v2
+
+      - name: Build, Tag, and Push Image to ECR
+        id: build-image
+        env:
+          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          ECR_REPOSITORY: fastapi
+          IMAGE_TAG: latest
+        run: |
+          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
+          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG 
