Build only if lint and pytest succeed

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -1,25 +1,24 @@
 name: Build and Push Docker Image to AWS ECR
 
 on:
-  - push
-  # workflow_run:
-  #   workflows:
-  #     - Python
-  #   types:
-  #     - completed
+  workflow_run:
+    workflows:
+      - Python
+    types:
+      - completed
 jobs:
   build-and-push:
     name: Build and Push to ECR
     runs-on: ubuntu-latest
     steps:
-      # - name: Check Workflow Python status
-      #   run: |
-      #     if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
-      #       echo "Workflow Python was successful."
-      #     else
-      #       echo "Workflow Python failed."
-      #       exit 1
-      #     fi
+      - name: Check Workflow Python Status
+        run: |
+          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
+            echo "Workflow Python was successful."
+          else
+            echo "Workflow Python failed."
+            exit 1
+          fi
       - name: Checkout repo
         uses: actions/checkout@v3
 
